@startuml Ecommerce

package "Plataforma de Comercio Electrónico" {

    [Frontend] -down-> [Autentificación]
    [Autentificación] -down-> [Servicio de venta]
    [Autentificación] -down-> [Seguimiento de venta]

    [Autentificación] -down-> [Base de Datos]
    [Servicio de venta] -right-> [Base de Datos]
    [Seguimiento de venta] -left-> [Base de Datos]
}

@enduml
